### ISSUE TITLE
[Backend Bug Report] Login Loops still exist

### ISSUE THREAD

**Issue by auisgold** [RealDeviceMap/RealDeviceMap#136] opened 2020-06-08 12:47 UTC
**Describe the bug**
Some devices still have login loops on Quest Instances

**To Reproduce**
1. Start a device in an quest instance
2. Device will try to scan_quest, but switch_account is also sent at the same time so quest is skipped
3. This will happen over and over while no quests are scanned

**Expected behavior**
Devices should not be logged out while trying to scan for quests. 

**System**
 - Running in docker :yes
 - Host OS: Ubuntu 16.04
 - RDM Version 1.11.3

**Additional context**

**Comment by 123FLO321** [comment] 2020-06-08 15:03
@auisgold using GD or GC

**Comment by auisgold** [comment] 2020-06-08 15:06
GD

**Comment by Dewpg** [comment] 2020-06-08 16:00
Can confirm, this still happens.

**Comment by 123FLO321** [comment] 2020-06-08 16:05
Pleas provide logs of this happening.

**Comment by auisgold** [comment] 2020-06-08 16:25
Perfectly good account logs in and then immediately logs out

 
![Capture](https://user-images.githubusercontent.com/21145714/84055632-58d5e480-a972-11ea-9c37-7bcffbc0b642.PNG)

**Comment by 123FLO321** [comment] 2020-06-08 16:42
Can you add a full log so i can take a look please?

**Comment by 123FLO321** [comment] 2020-06-08 16:42
Also the row in the db for this account

**Comment by auisgold** [comment] 2020-06-08 17:27
This is what the account in the db is like
[accounts.txt](https://github.com/RealDeviceMap/RealDeviceMap/files/4747512/accounts.txt)

There's not much more to the logs, this is a full cycle of getting an account, logging out and getting another one, account that logs in is always at the same stop, but the stop never gets spun. This will repeat in the logs over and over and the instance never gets a single quest finished. 
![image](https://user-images.githubusercontent.com/21145714/84061326-f7664380-a97a-11ea-953a-380dc33eee94.png)

**Comment by dondi99** [comment] 2020-06-09 01:13
I'm still having the login loop when questing. Does seem to be cooldown related - not sure which is the cause and which is the effect login loop vs cooldown. I put on a quest instance and went from 0 on cooldown to 5 on cooldown in a matter of minutes while the phone is logging 30s in and out.

**Comment by 123FLO321** [comment] 2020-06-09 04:01
Is. This macless or UIC?

**Comment by 123FLO321** [comment] 2020-06-09 04:04
And what is min and max level on the instance?

**Comment by auisgold** [comment] 2020-06-09 04:18
Macless, min level: 30, max level: 40 on the instance

**Comment by geekygreek7** [comment] 2020-06-09 04:56
Having similar issues. Stuck at login screen on many phones. Gonna look further into it now

**Comment by DrKendall** [comment] 2020-06-09 09:57
I was about to add to this. I have several Auto Instances that never complete:
Always shows something like: `Done: 634\|634/645 (98.3\|98.3%)` or `Done: 1452\|1460/1460 (99.5\|100.0%)`. 

I found that if I manually spun the stop (despite using UQ), it would jump to the next stop. Also, when I was using UIC, if I disabled UltraQuest, it would spin them just fine. 

My Min Max levels are 5 - 29 of all of mine.  

It seems to me there is an issue with the trigger GDS gets to UQ. 
G refuses to acknowledge this is an issue on their behalf, and insists the issue is with RDM.

**Comment by auisgold** [comment] 2020-06-09 14:16
I found something else that might help that if going from one quest instance to another then the device will loop instantly, but if you do a quest instance, then switch to a Pokémon instance for 5 minutes and then go to a quest instance then it won't loop until later

**Comment by dondi99** [comment] 2020-06-09 14:24
Not macless for me - UIC with L30 accounts. 
Instance settings:
Min Level 30
Max Level 40
Spin Limit 3500
Delay Logout 900

**Comment by dondi99** [comment] 2020-06-09 14:35
I have a UIC log starting at my switch from Pokemon to Quest through the first logout/account switch if it would help. It has identifying account and password info so I would like to DM it if it is needed.

**Comment by 123FLO321** [comment] 2020-06-09 16:19
@dondi99 yes please

**Comment by Pokekeqz** [comment] 2020-06-11 06:47
> @Pokekeqz confirm me the version shown in /dashboard

![6B850483-59CE-42D4-B779-B139D33D5C27](https://user-images.githubusercontent.com/46907107/84353803-17d30f80-abc0-11ea-9ab0-1e29a26c69ad.png)

**Comment by 123FLO321** [comment] 2020-06-11 10:02
@everyone: please use 1.12.1 for testing.
Should help understand the logs a bit better.

@auisgold can you update and show me the logs after the update?

**Comment by auisgold** [comment] 2020-06-11 11:01
Still getting exact same result as before, made sure that I had WebHookRequestHandler logs for devices that said Account is not valid for Instance. Switching Account so I am on the latest, but this is the log for a device that is in a Login loop, same as before. 

![image](https://user-images.githubusercontent.com/21145714/84377909-9b7d0400-aba0-11ea-85e2-9e9f5ecff144.png)

**Comment by 123FLO321** [comment] 2020-06-11 11:10
@auisgold is this a filtered log?
Please send me the full log

**Comment by auisgold** [comment] 2020-06-11 11:16
This is the result of "sudo docker logs realdevicemap | grep -F "[WebHookRequestHandler] [device_name]". Also seems that account is determined to be over Logout Delay always. 

![image](https://user-images.githubusercontent.com/21145714/84379207-a9cc1f80-aba2-11ea-8801-c353e24ebafb.png)

**Comment by auisgold** [comment] 2020-06-11 11:23
[login.log](https://github.com/RealDeviceMap/RealDeviceMap/files/4764390/login.log)

Here's a full log, beginning of log doesn't have login loop, login loops start around line 4300.

**Comment by 123FLO321** [comment] 2020-06-11 11:47
Mario db or mysql?

**Comment by 123FLO321** [comment] 2020-06-11 11:50
@auisgold and can you pm me an un-filtered log?

**Comment by auisgold** [comment] 2020-06-11 14:18
Mysql? You want my entire rdm log?

**Comment by nileplumb** [comment] 2020-07-07 13:02
Quests sucked today, I guess this is still an issue.

I'm trying to split into smaller quest areas now but I can't really string them together via auto complete

**Comment by 123FLO321** [comment] 2020-09-07 14:48
Fixed in 1.18.0

**Closed by 123FLO321** 2020-09-07 14:48 UTC
Labels: backend, bug
