### ISSUE TITLE
[Feature Request] Inscance results statistics

### ISSUE THREAD

**Issue by kamieniarz** [RealDeviceMap/RealDeviceMap#488] opened 2023-02-28 17:01 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem but a nice addition for monitoring things in order to improve general scans performance

**Describe the solution you'd like**
I'd love to have a stats table with statistics of anything that's an output for `Status` column in instances tab so generally what I care the most is round times for circle type instances, but actually questing instances could be a nice addition too. A simple table with instanceid/name, instance type, result (which would be a round time or quests status or so) and proly a timestamp would do the job I think. When it comes to circle instances each data set could be added on round time update. That should do the job perfectly so it could be added to grafana to monitor all that stuff more thoroughly

**Describe alternatives you've considered**
All I could think about is an external script that would have to grab these data from rdm's dashboard I guess

**Additional context**

**Comment by Fabio1988** [comment] 2023-02-28 17:37
Duplicate of #370

**Closed by Fabio1988** 2023-02-28 17:37 UTC
Labels: enhancement
